#!/usr/bin/env bash
# Displays username, user id, and home directory from /etc/passwd
while IFS=: read -r user pass uid gid info home shell || [ -n "$user" ]
do
    echo "${user}:${uid}:${home}"
done < /etc/passwd
