#!/usr/bin/env bash
# Gives information about a specific file passed via command line
if [ $# -gt 0 ]; then
    FILE=$1
    if [ -e "$FILE" ]
    then
        echo "$FILE file exists"
        if [ -s "$FILE" ]
        then
            echo "$FILE file is not empty"
        else
            echo "$FILE file is empty"
        fi
        if [ -f "$FILE" ]
        then
            echo "$FILE is a regular file"
        fi
    else
        echo "$FILE file does not exist"
    fi
fi
