#!/usr/bin/env bash
# This script displays the content of the file /etc/passwd
while IFS=: read -r user pass uid gid info home shell || [ -n "$user" ]
do
    echo "${user}:${uid}:${home}"
done < /etc/passwd
