#!/usr/bin/env bash
# Manages system runtime registration tracking files and signal behaviors
PID_FILE="/var/run/myscript.pid"

echo "$$" > "$PID_FILE"

clean_up() {
    rm -f "$PID_FILE"
    exit 0
}

trap 'echo "I hate the kill command"; clean_up' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap 'clean_up' SIGQUIT

while true
do
    echo "To infinity and beyond"
    sleep 2
done
